
CORE_PFAM_TSV = "corepfam.tsv"
BIO_PFAM_TSV = "biopfam.tsv"
FULL_TSV = "bigscape_distances.tsv"

# location of the sqlite database to analyze
SQLITE_DB = "C:/Temp/data-benchmark-100.db"
# Base folder of Cluster files generated by BiG-SCAPE for a run. e.g:
# BIGSCAPE_CLUSTER_FILES = "/home/crude/benchmark-out/dev-100/network_files/2022-03-21_18-17-21_hybrids_global/"
